import type { Lycee } from '../../types/lycee'

export async function getLyceesData(): Promise<Lycee[]> {
  // Pour l'instant, on retourne des données mock
  // Plus tard, on pourra connecter à une vraie base de données
  return [
    {
      id: 1,
      nom: "Etienne Dolet",
      type: "Public",
      arrondissement: "20e",
      rue: "77 avenue Gambetta",
      ville: "Paris",
      code_postal: "75020",
      telephone: "01 43 48 12 34",
      email: "contact@lycee-dolet.fr",
      site_web: "http://www.lycee-dolet.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "Histoire-Géographie", "Langues"],
      sections: ["Générale", "Technologique"],
      effectifs: 850,
      taux_reussite_bac: 89
    },
    {
      id: 2,
      nom: "Lycée privé Charles de Foucauld",
      type: "Privé sous contrat",
      arrondissement: "18e",
      rue: "1 place du Cardinal Amette",
      ville: "Paris",
      code_postal: "75018",
      telephone: "01 46 06 12 34",
      email: "contact@cfoucauld.fr",
      site_web: "http://www.cfoucauld.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SES", "Histoire-Géographie", "Langues", "Arts"],
      sections: ["Générale"],
      effectifs: 650,
      taux_reussite_bac: 95
    },
    {
      id: 3,
      nom: "Lycée polyvalent Guillaume Tirel",
      type: "Public",
      arrondissement: "14e",
      rue: "237 boulevard Raspail",
      ville: "Paris",
      code_postal: "75014",
      telephone: "01 43 95 12 34",
      email: "contact@lycee-tirel.fr",
      site_web: "http://www.lycee-tirel.fr",
      specialites: ["Hôtellerie-Restauration", "Gestion", "Langues"],
      sections: ["Technologique", "Professionnelle"],
      effectifs: 750,
      taux_reussite_bac: 87
    },
    {
      id: 4,
      nom: "Lycée polyvalent l'Initiative",
      type: "Privé",
      arrondissement: "19e",
      rue: "24 rue Bouret",
      ville: "Paris",
      code_postal: "75019",
      telephone: "01 42 08 12 34",
      email: "contact@initiative.fr",
      site_web: "http://www.initiative.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SES", "Numérique"],
      sections: ["Générale", "Technologique"],
      effectifs: 450,
      taux_reussite_bac: 92
    },
    {
      id: 5,
      nom: "Lycée polyvalent privé Saint Jean de Montmartre",
      type: "Privé sous contrat",
      arrondissement: "18e",
      rue: "71 rue Caulaincourt",
      ville: "Paris",
      code_postal: "75018",
      telephone: "01 46 06 45 67",
      email: "contact@sjmontmartre.fr",
      site_web: "http://www.sjmontmartre.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "SES", "Arts"],
      sections: ["Générale"],
      effectifs: 520,
      taux_reussite_bac: 94
    },
    {
      id: 6,
      nom: "Lycée privé Pascal",
      type: "Privé sous contrat",
      arrondissement: "16e",
      rue: "33 boulevard Lannes",
      ville: "Paris",
      code_postal: "75016",
      telephone: "01 45 04 12 34",
      email: "contact@pascal.fr",
      site_web: "http://www.pascal.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "SES", "Philosophie"],
      sections: ["Générale"],
      effectifs: 680,
      taux_reussite_bac: 96
    },
    {
      id: 7,
      nom: "Lycée du bâtiment et des travaux publics",
      type: "Public",
      arrondissement: "13e",
      rue: "25 rue de Patay",
      ville: "Paris",
      code_postal: "75013",
      telephone: "01 44 08 12 34",
      email: "contact@btp-paris.fr",
      site_web: "http://www.btp-paris.fr",
      specialites: ["Sciences de l'ingénieur", "Mathématiques", "Physique-Chimie"],
      sections: ["Technologique", "Professionnelle"],
      effectifs: 900,
      taux_reussite_bac: 85
    },
    {
      id: 8,
      nom: "Lycée polyvalent privé Saint-Nicolas",
      type: "Privé sous contrat",
      arrondissement: "6e",
      rue: "108 rue de Vaugirard",
      ville: "Paris",
      code_postal: "75006",
      telephone: "01 45 44 12 34",
      email: "contact@saintnicolas.fr",
      site_web: "http://www.saintnicolas.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SES", "Langues"],
      sections: ["Générale", "Technologique"],
      effectifs: 580,
      taux_reussite_bac: 93
    },
    {
      id: 9,
      nom: "Lycée privé La Rochefoucauld",
      type: "Privé sous contrat",
      arrondissement: "7e",
      rue: "19 rue de la Rochefoucauld",
      ville: "Paris",
      code_postal: "75009",
      telephone: "01 48 74 12 34",
      email: "contact@larochefoucauld.fr",
      site_web: "http://www.larochefoucauld.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "Langues"],
      sections: ["Générale"],
      effectifs: 620,
      taux_reussite_bac: 95
    },
    {
      id: 10,
      nom: "Lycée technique privé de l'école technique supérieure du laboratoire",
      type: "Privé",
      arrondissement: "15e",
      rue: "12 rue Saint-Lambert",
      ville: "Paris",
      code_postal: "75015",
      telephone: "01 45 32 12 34",
      email: "contact@etsl.fr",
      site_web: "http://www.etsl.fr",
      specialites: ["Sciences de laboratoire", "Physique-Chimie", "SVT", "Mathématiques"],
      sections: ["Technologique"],
      effectifs: 280,
      taux_reussite_bac: 88
    },
    {
      id: 11,
      nom: "Lycée privé Charles Péguy",
      type: "Privé sous contrat",
      arrondissement: "11e",
      rue: "80 avenue Parmentier",
      ville: "Paris",
      code_postal: "75011",
      telephone: "01 48 05 12 34",
      email: "contact@charlespeguy.fr",
      site_web: "http://www.charlespeguy.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SES", "Histoire-Géographie"],
      sections: ["Générale"],
      effectifs: 540,
      taux_reussite_bac: 93
    },
    {
      id: 12,
      nom: "Lycée privé Sainte-Louise",
      type: "Privé sous contrat",
      arrondissement: "20e",
      rue: "28 rue des Couronnes",
      ville: "Paris",
      code_postal: "75020",
      telephone: "01 43 58 12 34",
      email: "contact@saintelouise.fr",
      site_web: "http://www.saintelouise.fr",
      specialites: ["Mathématiques", "SVT", "SES", "Langues", "Arts"],
      sections: ["Générale"],
      effectifs: 380,
      taux_reussite_bac: 94
    },
    {
      id: 13,
      nom: "Lycée privé L'Ecole alsacienne",
      type: "Privé",
      arrondissement: "6e",
      rue: "109 rue Notre-Dame des Champs",
      ville: "Paris",
      code_postal: "75006",
      telephone: "01 44 32 12 34",
      email: "contact@ecole-alsacienne.fr",
      site_web: "http://www.ecole-alsacienne.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "Langues", "Arts", "Philosophie"],
      sections: ["Générale"],
      effectifs: 720,
      taux_reussite_bac: 98
    },
    {
      id: 14,
      nom: "Lycée polyvalent ESAA-Ecole Boulle",
      type: "Public",
      arrondissement: "12e",
      rue: "9-21 rue Pierre Bourdan",
      ville: "Paris",
      code_postal: "75012",
      telephone: "01 44 08 81 82",
      email: "contact@boulle.fr",
      site_web: "http://www.boulle.fr",
      specialites: ["Arts appliqués", "Design", "Métiers d'art", "STD2A"],
      sections: ["Technologique", "Professionnelle"],
      effectifs: 950,
      taux_reussite_bac: 91
    },
    {
      id: 15,
      nom: "Lycée polyvalent Paul Poiret",
      type: "Public",
      arrondissement: "11e",
      rue: "26 rue des Taillandiers",
      ville: "Paris",
      code_postal: "75011",
      telephone: "01 49 29 12 34",
      email: "contact@paulpoiret.fr",
      site_web: "http://www.paulpoiret.fr",
      specialites: ["Mode", "Arts appliqués", "Design", "Commerce"],
      sections: ["Technologique", "Professionnelle"],
      effectifs: 650,
      taux_reussite_bac: 86
    },
    {
      id: 16,
      nom: "Lycée Charlemagne",
      type: "Public",
      arrondissement: "4e",
      rue: "14 rue Charlemagne",
      ville: "Paris",
      code_postal: "75004",
      telephone: "01 53 01 98 20",
      email: "contact@charlemagne.fr",
      site_web: "http://www.charlemagne.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "Histoire-Géographie", "Langues", "Philosophie"],
      sections: ["Générale"],
      effectifs: 1200,
      taux_reussite_bac: 97
    },
    {
      id: 17,
      nom: "Lycée Claude Monet",
      type: "Public",
      arrondissement: "13e",
      rue: "1 rue du Docteur Magnan",
      ville: "Paris",
      code_postal: "75013",
      telephone: "01 44 08 47 00",
      email: "contact@claudemonet.fr",
      site_web: "http://www.claudemonet.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "SES", "Arts"],
      sections: ["Générale"],
      effectifs: 890,
      taux_reussite_bac: 91
    },
    {
      id: 18,
      nom: "Lycée privé Lucien de Hirsch",
      type: "Privé sous contrat",
      arrondissement: "19e",
      rue: "70 avenue Secrétan",
      ville: "Paris",
      code_postal: "75019",
      telephone: "01 42 08 12 34",
      email: "contact@luciendehirsch.fr",
      site_web: "http://www.luciendehirsch.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SES", "Langues"],
      sections: ["Générale", "Technologique"],
      effectifs: 420,
      taux_reussite_bac: 89
    },
    {
      id: 19,
      nom: "Lycée privé Saint-Michel de Picpus",
      type: "Privé sous contrat",
      arrondissement: "12e",
      rue: "51 rue de Picpus",
      ville: "Paris",
      code_postal: "75012",
      telephone: "01 44 73 12 34",
      email: "contact@saintmichelpicpus.fr",
      site_web: "http://www.saintmichelpicpus.fr",
      specialites: ["Mathématiques", "Physique-Chimie", "SVT", "SES", "Langues"],
      sections: ["Générale"],
      effectifs: 480,
      taux_reussite_bac: 92
    }
  ]
}